### ISSUE TITLE
Additional endpoints support

### ISSUE THREAD

**Issue by arnasledev** [coingate/coingate-node#4]
## Feature Request

**Is your feature request related to a problem? Please describe.**

You can not fetch your withdrawals or account details using this SDK even API supports that

**Describe the solution you'd like**

additional endpoints support should solve the issue.

1. https://developer.coingate.com/reference/get-account
2. https://developer.coingate.com/reference/get-withdrawals
3. https://developer.coingate.com/reference/accounts
4. https://developer.coingate.com/reference/get-withdrawal

## Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by vgumonis** [comment]
@arnasledev, please also update the README on how to import the module, some users are getting confused
